version: '3.8'

services:
  app:
    build: ./go-server
    ports:
      - "8080:8080"
    environment:
      - DB_URI=mongodb://db:27017
      - DB_NAME=test
      - DB_COLLECTION_NAME=todolist
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
