version: '3.8'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  client:
    image: client:latest
    ports:
      - "3000:3000"

  app:
    image: go-server:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URI=mongodb://db:27017
      - DB_NAME=test
      - DB_COLLECTION_NAME=todolist

volumes:
  mongo-data:
