name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        run: |
          docker compose up --build -d
          docker tag app-client:latest 730335558791.dkr.ecr.eu-central-1.amazonaws.com/my-dev-repository-client:latest
          docker tag mongo:latest 730335558791.dkr.ecr.eu-central-1.amazonaws.com/my-dev-repository-db:latest
          docker tag app-app:latest 730335558791.dkr.ecr.eu-central-1.amazonaws.com/my-dev-repository-app:latest
          docker push 730335558791.dkr.ecr.eu-central-1.amazonaws.com/my-dev-repository-app
          docker push 730335558791.dkr.ecr.eu-central-1.amazonaws.com/my-dev-repository-client
          docker push 730335558791.dkr.ecr.eu-central-1.amazonaws.com/my-dev-repository-db